name: TntRun
main: org.sobadfish.tntrun.TntRunMain
version: 1.0.6
api:
  - 1.0.11
  - 3.0.0
author: sobadfish
load: POSTWORLD
description: "TNT 跑酷"

softdepend:
  - ScoreboardPlugin

loadbefore:
  - ScoreboardPlugin
